Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [46]:
import numpy as np

In [47]:
n=10
x=np.arange(n-1,-1, -1)
print(x)

[9 8 7 6 5 4 3 2 1 0]


Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

По скольку из условия задачи не ясно, входит ли элемент n в матрицу,то два варианта решения - с вхождением n и нет.

In [53]:
n=3
y=np.diag(np.arange(n, -1, -1), k=0)
print(y)

[[3 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 0]]


In [54]:
sum=y.sum()
print(sum)

6


In [56]:
n=3
y=np.diag(np.arange(n-1, -1, -1), k=0)
print(y)
sum=y.sum()
print(sum)

[[2 0 0]
 [0 1 0]
 [0 0 0]]
3


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [57]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
from numpy import linalg


In [58]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [59]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

Задача 4 домашнего задания
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [60]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [61]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [62]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [64]:
i = 0
max = 0
maxi = 0
for j in users_stats:
    print(i)
    print(j)
    print(next_user_stats)
    cos = cosine(j, next_user_stats)
    print('Косинус', cos)
    if cos > max:
        max = cos
        maxi = i
    i+=1
print('Самый похожий пользователь id =', maxi)

0
[2 1 0 0 0 0]
[0 1 2 0 0 0]
Косинус 0.19999999999999996
1
[1 1 2 1 0 0]
[0 1 2 0 0 0]
Косинус 0.8451542547285165
2
[2 0 1 0 0 0]
[0 1 2 0 0 0]
Косинус 0.3999999999999999
3
[1 1 2 1 0 1]
[0 1 2 0 0 0]
Косинус 0.7905694150420948
4
[0 0 1 2 0 0]
[0 1 2 0 0 0]
Косинус 0.3999999999999999
5
[0 0 0 0 0 5]
[0 1 2 0 0 0]
Косинус 0.0
6
[1 0 0 0 0 0]
[0 1 2 0 0 0]
Косинус 0.0
7
[0 1 1 0 0 0]
[0 1 2 0 0 0]
Косинус 0.9486832980505138
8
[0 0 0 1 1 3]
[0 1 2 0 0 0]
Косинус 0.0
9
[1 0 0 2 1 4]
[0 1 2 0 0 0]
Косинус 0.0
Самый похожий пользователь id = 7
